services:
  gitea-server:
    image: gitea/gitea:latest
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=gitea-postgres:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - DISABLE_REGISTRATION=true
    restart: always
    networks:
      default:
        ipv4_address: 172.20.1.21
      gitea:
    volumes:
      - ./gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - gitea-postgres

  gitea-postgres:
    image: postgres:14-alpine
    container_name: gitea-postgres
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      gitea:
    volumes:
      - ./gitea-postgres:/var/lib/postgresql/data
    labels:
      com.centurylinklabs.watchtower.enable: "true"

networks:
  default:
     name: nginx_default
     external: true
  gitea:
